name             'mybook'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures cookbook_name'
long_description 'Installs/Configures cookbook_name'
version          '0.1.0'

depends 'windows-hardening'
depends 'windows'
depends 'firewall'