name             'mybook'
maintainer       'You'
maintainer_email 'youtname@email.com'
license          'All rights reserved'
description      'Configures XYZ'
long_description 'Configures XYZ ABC DEF'
version          '0.1.1'
issues_url       'http://noaddress.io'
source_url       'http://noaddress.io'

depends 'windows'
depends 'firewall'
depends 'windows_firewall'
depends 'chef-sugar'
